vich_uploader:
    db_driver: orm

    mappings:
       medias:
           uri_prefix: /images/medias
           upload_destination: '%kernel.project_dir%/public/docs/medias'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
